name: deploy
run-name: ${{github.actor}} deploy package to npm
on:
  push:
    branches:
      - env/prod
jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm run test:cov
      - run: npm run build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.ACCESS_TOKEN}}